// <auto-generated />
using GifStorage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GifStorage.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("GifStorage.Data.Entities.Gif", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gifs");
                });

            modelBuilder.Entity("GifStorage.Data.Entities.GifTag", b =>
                {
                    b.Property<long>("GifId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GifId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GifTags");
                });

            modelBuilder.Entity("GifStorage.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GifTag", b =>
                {
                    b.Property<long>("GifsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GifsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("GifTag");
                });

            modelBuilder.Entity("GifStorage.Data.Entities.GifTag", b =>
                {
                    b.HasOne("GifStorage.Data.Entities.Gif", "Gif")
                        .WithMany("GifTags")
                        .HasForeignKey("GifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GifStorage.Data.Entities.Tag", "Tag")
                        .WithMany("GifTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gif");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GifTag", b =>
                {
                    b.HasOne("GifStorage.Data.Entities.Gif", null)
                        .WithMany()
                        .HasForeignKey("GifsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GifStorage.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GifStorage.Data.Entities.Gif", b =>
                {
                    b.Navigation("GifTags");
                });

            modelBuilder.Entity("GifStorage.Data.Entities.Tag", b =>
                {
                    b.Navigation("GifTags");
                });
#pragma warning restore 612, 618
        }
    }
}
